on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.1.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kobo-data-extraction-api" #Must be unique in Heroku
          heroku_email: "nicolas.knoxx@gmail.com"
        env:
          HD_PORT: ${{ secrets.PORT }}
          HD_HOST: ${{ secrets.HOST }}
          HD_KOBO_BASEURL: ${{ secrets.KOBO_BASEURL }}
          HD_KOBO_USER: ${{ secrets.KOBO_USER }}
          HD_KOBO_PASSWORD: ${{ secrets.KOBO_PASSWORD }}
          HD_MONGO_DB_CONNECTIONSTRING: ${{ secrets.MONGO_DB_CONNECTIONSTRING }}
